(define (problem pb1)
    (:domain generated-domain)
    (:requirements :strips :negative-preconditions)
    (:init
       (not (p0))
       (p1)
       (p2)
       (p3)
       (not (p4))
       (not (p5))
       (p6)
       (not (p7))
       (p8)
       (not (p9))
       (p10)
       (not (p11))
       (not (p12))
       (not (p13))
       (p14)
       (p15)
       (not (p16))
       (p17)
       (p18)
       (not (p19))
       (not (p20))
       (p21)
       (p22)
       (not (p23))
       (p24)
       (p25)
       (not (p26))
       (p27)
       (not (p28))
       (p29)
       (not (p30))
       (not (p31))
       (p32)
       (p33)
       (p34)
       (p35)
    )
    (:goal
      (and
       (not (p0))
       (p1)
       (p2)
       (p3)
       (not (p4))
       (p5)
       (p6)
       (not (p7))
       (p8)
       (not (p9))
       (p10)
       (not (p11))
       (p12)
       (p13)
       (p14)
       (p15)
       (p16)
       (not (p17))
       (not (p18))
       (not (p19))
       (not (p20))
       (p21)
       (p22)
       (not (p23))
       (p24)
       (not (p25))
       (not (p26))
       (p27)
       (not (p28))
       (p29)
       (not (p30))
       (not (p31))
       (p32)
       (p33)
       (p34)
       (p35)
      )
    )
)