(define (domain lights)
  (:requirements :strips :negative-preconditions :equality)

  (:predicates
    (on ?c)
    (adjacent ?a ?b)
    (corner ?c)
    (border ?b)
    (center ?c)
  )

  (:action click-on-corner-2on
    :parameters (?c ?n1 ?n2)
    :precondition (and
      (corner ?c)
      (on ?c)
      (on ?n1)
      (on ?n2)
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (not (= ?n1 ?n2))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
    )
  )

  (:action click-on-corner-1on
    :parameters (?c ?n1 ?n2)
    :precondition (and
      (corner ?c)
      (on ?c)
      (on ?n1)
      (not (on ?n2))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (not (= ?n1 ?n2))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (on ?n2)
    )
  )

  (:action click-on-corner-0on
    :parameters (?c ?n1 ?n2)
    :precondition (and
      (corner ?c)
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (not (= ?n1 ?n2))
    )
    :effect (and
      (not (on ?c))
      (on ?n1)
      (on ?n2)
    )
  )

  (:action click-off-corner-2on
    :parameters (?c ?n1 ?n2)
    :precondition (and
      (corner ?c)
      (not (on ?c))
      (on ?n1)
      (on ?n2)
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (not (= ?n1 ?n2))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
    )
  )

  (:action click-off-corner-1on
    :parameters (?c ?n1 ?n2)
    :precondition (and
      (corner ?c)
      (not (on ?c))
      (on ?n1)
      (not (on ?n2))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (not (= ?n1 ?n2))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (on ?n2)
    )
  )

  (:action click-off-corner-0on
    :parameters (?c ?n1 ?n2)
    :precondition (and
      (corner ?c)
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (not (= ?n1 ?n2))
    )
    :effect (and
      (on ?c)
      (on ?n1)
      (on ?n2)
    )
  )

  (:action click-on-border-3on
    :parameters (?c ?n1 ?n2 ?n3)
    :precondition (and
      (border ?c)
      (on ?c)
      (on ?n1)
      (on ?n2)
      (on ?n3)
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n2 ?n3))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
    )
  )

  (:action click-on-border-2on
    :parameters (?c ?n1 ?n2 ?n3)
    :precondition (and
      (border ?c)
      (on ?c)
      (on ?n1)
      (on ?n2)
      (not (on ?n3))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n2 ?n3))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
      (on ?n3)
    )
  )

  (:action click-on-border-1on
    :parameters (?c ?n1 ?n2 ?n3)
    :precondition (and
      (border ?c)
      (on ?c)
      (on ?n1)
      (not (on ?n2))
      (not (on ?n3))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n2 ?n3))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (on ?n2)
      (on ?n3)
    )
  )

  (:action click-on-border-0on
    :parameters (?c ?n1 ?n2 ?n3)
    :precondition (and
      (border ?c)
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n2 ?n3))
    )
    :effect (and
      (not (on ?c))
      (on ?n1)
      (on ?n2)
      (on ?n3)
    )
  )

  (:action click-off-border-3on
    :parameters (?c ?n1 ?n2 ?n3)
    :precondition (and
      (border ?c)
      (not (on ?c))
      (on ?n1)
      (on ?n2)
      (on ?n3)
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n2 ?n3))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
    )
  )

  (:action click-off-border-2on
    :parameters (?c ?n1 ?n2 ?n3)
    :precondition (and
      (border ?c)
      (on ?c)
      (on ?n1)
      (on ?n2)
      (not (on ?n3))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n2 ?n3))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
      (on ?n3)
    )
  )

  (:action click-off-border-1on
    :parameters (?c ?n1 ?n2 ?n3)
    :precondition (and
      (border ?c)
      (not (on ?c))
      (on ?n1)
      (not (on ?n2))
      (not (on ?n3))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n2 ?n3))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (on ?n2)
      (on ?n3)
    )
  )

  (:action click-off-border-0on
    :parameters (?c ?n1 ?n2 ?n3)
    :precondition (and
      (border ?c)
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n2 ?n3))
    )
    :effect (and
      (on ?c)
      (on ?n1)
      (on ?n2)
      (on ?n3)
    )
  )

  (:action click-on-center-4on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (on ?c)
      (on ?n1)
      (on ?n2)
      (on ?n3)
      (on ?n4)
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
      (not (on ?n4))
    )
  )

  (:action click-on-center-3on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (on ?c)
      (on ?n1)
      (on ?n2)
      (on ?n3)
      (not (on ?n4))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
      (on ?n4)
    )
  )

  (:action click-on-center-2on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (on ?c)
      (on ?n1)
      (on ?n2)
      (not (on ?n3))
      (not (on ?n4))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
      (on ?n3)
      (on ?n4)
    )
  )

  (:action click-on-center-1on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (on ?c)
      (on ?n1)
      (not (on ?n2))
      (not (on ?n3))
      (not (on ?n4))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (not (on ?c))
      (not (on ?n1))
      (on ?n2)
      (on ?n3)
      (on ?n4)
    )
  )

  (:action click-on-center-0on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
      (not (on ?n4))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (not (on ?c))
      (on ?n1)
      (on ?n2)
      (on ?n3)
      (on ?n4)
    )
  )

  (:action click-off-center-4on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (not (on ?c))
      (on ?n1)
      (on ?n2)
      (on ?n3)
      (on ?n4)
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
      (not (on ?n4))
    )
  )

  (:action click-off-center-3on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (not (on ?c))
      (on ?n1)
      (on ?n2)
      (on ?n3)
      (not (on ?n4))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
      (on ?n4)
    )
  )

  (:action click-off-center-2on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (not (on ?c))
      (on ?n1)
      (on ?n2)
      (not (on ?n3))
      (not (on ?n4))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (not (on ?n2))
      (on ?n3)
      (on ?n4)
    )
  )

  (:action click-off-center-1on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (not (on ?c))
      (on ?n1)
      (not (on ?n2))
      (not (on ?n3))
      (not (on ?n4))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (on ?c)
      (not (on ?n1))
      (on ?n2)
      (on ?n3)
      (on ?n4)
    )
  )

  (:action click-off-center-0on
    :parameters (?c ?n1 ?n2 ?n3 ?n4)
    :precondition (and
      (center ?c)
      (not (on ?c))
      (not (on ?n1))
      (not (on ?n2))
      (not (on ?n3))
      (not (on ?n4))
      (adjacent ?c ?n1)
      (adjacent ?c ?n2)
      (adjacent ?c ?n3)
      (adjacent ?c ?n4)
      (not (= ?n1 ?n2))
      (not (= ?n1 ?n3))
      (not (= ?n1 ?n4))
      (not (= ?n2 ?n3))
      (not (= ?n2 ?n4))
      (not (= ?n3 ?n4))
    )
    :effect (and
      (on ?c)
      (on ?n1)
      (on ?n2)
      (on ?n3)
      (on ?n4)
    )
  )
)
